### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pgoodman** [trailofbits/qt-multiplier#364]
- [ ] quality-of-life improvements (higher priority)
  - [x] better sort order on things in info explorer -- match how understand orders stuff (https://github.com/trailofbits/qt-multiplier/pull/369) 
  - [x]  keybinding for toggling highlighting the entity under the cursor -- auto choose a color; if currently highlighted, then color is removed (https://github.com/trailofbits/qt-multiplier/pull/376)
  - [x] `(filename:line)` references in info browser (https://github.com/trailofbits/qt-multiplier/pull/369)
  - [x] more "copy details" and general info around, e.g. how do you know what the file path is of an open file? (https://github.com/trailofbits/qt-multiplier/pull/372)
  - [ ] configurability of preview behaviour on reference explorer
  - [x] location of popup buttons on generator widgets -- make it on the left side (https://github.com/trailofbits/qt-multiplier/pull/375)
  - [x] global history keybindings
  - [x] find and fix memory leaks (https://github.com/trailofbits/qt-multiplier/pull/373, https://github.com/trailofbits/qt-multiplier/pull/374)
  - [ ] find and fix performance problems / lag / "missed click" behaviours in code widgets
  - [ ] clicking on an entity shouldn't go to the beginning of the entity if we're already on the entity's name in the same line
  - [ ] common keybindings in code widget (e.g. shift+arrow for selections, double-click for whole-word select, triple click for line select, vim or other common keybindings for cursor navigation)
  - [ ] resizing the viewport of code widget should try to keep current line visible
  - [ ] history is a bit wonky sometimes
  - [ ] persistence: when you close and reopen, state should be brought back (renamings, colorings, etc.)
  - [ ] configurability: stuff can actually be configured
  - [x] clickable indicator on mouse hover in code widget (https://github.com/trailofbits/qt-multiplier/pull/371)
  - [ ] code preview should open with the reference in the center of the code
- [ ] c++ support
  - [ ] figure out what it means to look at different instantiations of a template -- probably needs lots of user testing
  - [ ] enable "look at all", "look at specific", etc.
- [ ] various widgets
  - [ ] callee hierarchy
  - [ ] entity renaming
  - [ ] add cross reference
  - [ ] bookmarks / bookmark folders
  - [ ] python console
  - [ ] code search
- [ ] annotations: so you can edit in notes inline with the code
- [ ] extensibility
  - [ ] run python scripts to "do things", e.g. highlight code areas of interest
  - [ ] python plugins to add gui functionality
